// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qosmvuddypvivhlytyyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvc212dWRkeXB2aXZobHl0eXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzYwNDcsImV4cCI6MjA3MzcxMjA0N30.6P-i59t-tXMaMIZzuliIIPC4XZFWai1k-V3evlDCEBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});